import type { CandidateTheme } from "./store";

export const CATALOG: CandidateTheme[] = [
  {
    id: "c1",
    name: "속삭이는 다락방",
    cafe: "달빛방탈출 성수점",
    genre: "공포",
    difficulty: 4,
    fearLevel: 5,
    tags: ["귀신", "청각연출", "몰입"],
    teaser: "낡은 다락방에서 들려오는 작은 목소리. 심장 단단히 챙겨오세요.",
    hint: "소리에 집중하면 순서가 보입니다. 서두르지 말고 귀 기울이기.",
    spoiler: "축음기 3개를 소리 순서대로 작동시키면 다락문이 열립니다.",
  },
  {
    id: "c2",
    name: "사라진 마카롱",
    cafe: "몽글이스케이프 연남점",
    genre: "감성",
    difficulty: 2,
    fearLevel: 1,
    tags: ["아기자기", "디저트", "힐링"],
    teaser: "파티시에의 비밀 레시피를 찾아 떠나는 달콤한 방.",
    hint: "색깔 순서가 곧 레시피입니다. 진열장을 잘 보세요.",
    spoiler: "마카롱 색을 무지개 순서로 놓으면 금고가 열립니다.",
  },
  {
    id: "c3",
    name: "은하수 배달부",
    cafe: "코스모방탈출 홍대점",
    genre: "SF",
    difficulty: 3,
    fearLevel: 1,
    tags: ["우주", "장치", "협동"],
    teaser: "고장난 우주선, 남은 산소는 60분. 지구로 돌아갈 수 있을까요?",
    hint: "별자리 패널이 콘솔 좌표와 연결돼 있습니다.",
    spoiler: "오리온자리 좌표를 콘솔에 입력하면 엔진이 재가동됩니다.",
  },
  {
    id: "c4",
    name: "고양이 탐정 사무소",
    cafe: "냥트릭 강남점",
    genre: "추리",
    difficulty: 3,
    fearLevel: 1,
    tags: ["동물", "추리", "귀여움"],
    teaser: "사라진 참치캔의 행방을 쫓는 탐정이 되어보세요.",
    hint: "발자국 방향과 시계 시간이 알리바이를 말해줍니다.",
    spoiler: "3시 방향 발자국의 주인이 범인, 자물쇠 번호는 0300.",
  },
  {
    id: "c5",
    name: "폐병원 301호",
    cafe: "다크룸 부평점",
    genre: "공포",
    difficulty: 5,
    fearLevel: 5,
    tags: ["고난도", "귀신", "배우연출"],
    teaser: "불 꺼진 병동, 사라진 환자 기록. 배우 연출 포함 하드코어.",
    hint: "차트 번호는 흩어진 X-ray에 숨어 있습니다.",
    spoiler: "X-ray 4장의 숫자를 더하면 병실 캐비닛 비번입니다.",
  },
  {
    id: "c6",
    name: "구름 위 우체국",
    cafe: "몽글이스케이프 연남점",
    genre: "감성",
    difficulty: 2,
    fearLevel: 1,
    tags: ["편지", "따뜻함", "입문"],
    teaser: "전하지 못한 편지들을 배달하는 포근한 이야기.",
    hint: "우표 그림이 곧 배달 순서입니다.",
    spoiler: "계절 우표를 봄여름가을겨울로 꽂으면 마지막 편지가 나옵니다.",
  },
  {
    id: "c7",
    name: "웃음도둑을 잡아라",
    cafe: "깔깔방탈출 건대점",
    genre: "코믹",
    difficulty: 2,
    fearLevel: 1,
    tags: ["코믹", "가족", "쉬움"],
    teaser: "마을의 웃음을 훔쳐간 도둑을 잡으러 출동.",
    hint: "썰렁한 농담 카드의 펀치라인을 이어보세요.",
    spoiler: "농담 3개의 첫 글자를 모으면 'ㅋㅋㅋ' 다이얼 정답.",
  },
  {
    id: "c8",
    name: "잊혀진 등대",
    cafe: "파도소리 속초점",
    genre: "모험",
    difficulty: 4,
    fearLevel: 2,
    tags: ["모험", "바다", "장치"],
    teaser: "폭풍 치는 밤, 꺼진 등대에 다시 불을 밝혀야 합니다.",
    hint: "모스부호와 등대 점멸 패턴이 짝을 이룹니다.",
    spoiler: "모스부호 'SOS'를 레버로 재현하면 등대에 불이 들어옵니다.",
  },
];
